# The math in Python-Numpy

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.

## 0 import the numpy

In [2]:
import numpy as np

## 1 The Array in numpy

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.

The matrix in numpy is the array of number, we can use `np.array ()` to create a **numpy array** from any type of array, such as

$$\begin{bmatrix}
1 && 2 \\
3 && 4
\end{bmatrix}$$

### 1.1 Create the numpy array

Arrays in Numpy can be created by multiple ways, with various number of Ranks, defining the size of the Array. Arrays can also be created with the use of various data types such as **lists, tuples**, etc. The type of the resultant array is deduced from the type of the elements in the sequences.

> Note: Type of array can be explicitly defined while creating the array.



In [3]:
array_list = np.array ([1, 2, 3, 4])
array_tuple = np.array ((5, 6, 7, 8))
m_a = np.array ([[1, 2],
                 [3, 4]])

"""
(function) def array(
    object: object,
    dtype: None = ...,
    *,
    copy: bool | _CopyMode = ...,
    order: _OrderKACF = ...,
    subok: bool = ...,
    ndmin: int = ...,
    like: _SupportsArrayFunc | None = ...
) -> NDArray[Any]
"""

print ("Numpy Array from list :\n", array_list)
print ("Numpy Array from tuple :\n", array_tuple)
print ("Numpy Array as matrix :\n", m_a)

Numpy Array from list :
 [1 2 3 4]
Numpy Array from tuple :
 [5 6 7 8]
Numpy Array as matrix :
 [[1 2]
 [3 4]]


The vector in numpy is the same as matrix because the vector is just a special matrix which has only one row or one column, such as

$$\vec{a} = (1, 2, 3, 4)$$

In [5]:
vec_a = np.array ([1, 2, 3, 4])
print ("Numpy Array as vector :\n", vec_a)

Numpy Array as vector :
 [1 2 3 4]


Beyond the normal array, we can also create the specific array by the function, such as the array with **Only Zero** , the array with **Same Value** , the array with **Random Value**

In [12]:
zero_array = np.zeros ((3, 4))
"""
(function) def zeros(
    shape: _ShapeLike,
    dtype: None = ...,
    order: _OrderCF = ...,
    *,
    like: _SupportsArrayFunc | None = ...
) -> NDArray[float64]
"""

same_array = np.full ((3, 3), 6)
"""
(function) def full(
    shape: _ShapeLike,
    fill_value: Any,
    dtype: None = ...,
    order: _OrderCF = ...,
    *,
    like: _SupportsArrayFunc = ...
) -> NDArray[Any]
"""

random_array1 = np.random.random ((2, 2))
"""
def random(size: None = ...) -> float: ...
"""
random_array2 = np.random.rand (2, 2)
"""
def rand(*args: int) -> ndarray[Any, dtype[float64]]: ...

`*args` - the dimensions of the array
"""

random_array3 = np.empty ((2, 2))
"""
(function) def empty(
    shape: _ShapeLike,
    dtype: None = ...,
    order: _OrderCF = ...,
    *,
    like: _SupportsArrayFunc | None = ...
) -> NDArray[float64]
"""

print ("The array with 0 :\n", zero_array)
print ("The array with same value :\n", same_array)
print ("The array with random value from `np.random.random` :\n", random_array1)
print ("The array with random value from `np.random.rand` :\n", random_array2)
print ("The array with random value from `np.empty` :\n", random_array3)

The array with 0 :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
The array with same value :
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
The array with random value from `np.random.random` :
 [[0.32857303 0.8369507 ]
 [0.42614772 0.79020535]]
The array with random value from `np.random.rand` :
 [[0.54999908 0.3631753 ]
 [0.59411659 0.58117413]]
The array with random value from `np.empty` :
 [[0.34230131 0.66269926]
 [0.10701934 0.54517769]]


Additionally, we can create an array by the given range, such as **range from a to b with the stride n**, or **slice up the range** into many pieces : 

In [14]:
arange_array = np.arange (2, 10, 2)
"""
(function) def arange(
    start: _IntLike_co,
    stop: _IntLike_co,
    step: _IntLike_co = ...,
    dtype: None = ...,
    *,
    like: _SupportsArrayFunc | None = ...
) -> NDArray[signedinteger[Any]]

`start` and `stop` are optional
"""

linspace_array = np.linspace (10, 100, 10)
"""
(function) def linspace(
    start: _ArrayLikeFloat_co,
    stop: _ArrayLikeFloat_co,
    num: SupportsIndex = ...,
    endpoint: bool = ...,
    retstep: Literal[False] = ...,
    dtype: None = ...,
    axis: SupportsIndex = ...
) -> NDArray[floating[Any]]
"""

print ("The array from `arange` :\n", arange_array)
print ("The array from `linspace` :\n", linspace_array)

The array from `arange` :
 [2 4 6 8]
The array from `linspace` :
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


### 1.2 Access Numpy Array

In a numpy array, indexing or accessing the array index can be done in multiple ways. To print a range of an array, **slicing** is done. Slicing of an array is defining a range in a new array which is used to print a range of elements from the original array. Since, sliced array holds a range of elements of the original array, modifying content with the help of sliced array modifies the original array content.

In [10]:
print ("The Third Value of vec_a :\n", vec_a[2])
print ("The 0 - 1 value of vec_a :\n", vec_a[:2])

print ("The row2, col1 value of m_a :\n", m_a[1, 0])
print ("The row2, col 1 - 2 of m_a :\n", m_a[0, :2])

The Third Value of vec_a :
 3
The 0 - 1 value of vec_a :
 [1 2]
The row2, col1 value of m_a :
 3
The row2, col 1 - 2 of m_a :
 [1 2]


## 02 Operation of Numpy Array

### 2.1 Basic Operation

The basic operations on an array are : 

1. add a number on it
2. add two arrays on
3. times a number on it
4. times two arrays

In [18]:
arry1 = np.array ([1, 2, 3, 4])
arry2 = np.array ([5, 6, 7, 8])

# Add a number on arry1
arry_add_num = arry1 + 1
print ("Add a number on arry1 :\n", arry_add_num)

# Add two arrays
arry_add = arry1 + arry2
print ("Add two arrays :\n", arry_add)

# Times a number on it
arry_times_num = 3 * arry1
print ("Times a number on it :\n", arry_times_num)

Add a number on arry1 :
 [2 3 4 5]
Add two arrays :
 [ 6  8 10 12]
Times a number on it :
 [ 3  6  9 12]


Times two array are two methods : 

1. matrix multiplication
2. dot product

In [30]:
arry_dot1 = np.dot (arry1, arry2)
"""
(function) def dot(
    a: ArrayLike,
    b: ArrayLike,
    out: None = ...
) -> Any
"""
print ("Dot product of arrays :\n", arry_dot1)

arry_2d_1 = np.array ([[1, 2, 3, 4], 
                       [5, 6, 7, 8]])
arry_2d_2 = np.array ([[2,3], 
                       [4, 5], 
                       [6, 7], 
                       [8, 9]])
arry_dot2 = np.dot (arry_2d_1, arry_2d_2)
print ("Matrix Multiplication of 2D array :\n", arry_dot2)

arry_2d_3 = np.array ([[2, 3, 4, 5], 
                       [6, 7, 8, 9]])
arry_multiply = arry_2d_1 * arry_2d_3
print ("Dot product of 2D arrays :\n", arry_multiply)

Dot product of arrays :
 70
Matrix Multiplication of 2D array :
 [[ 60  70]
 [140 166]]
Dot product of 2D arrays :
 [[ 2  6 12 20]
 [30 42 56 72]]


### 2.2 Advaced Operation

#### 1. Reshape

We can reshape the array to what we want by `np.reshape` function : 

In [39]:
arr = np.array([[1, 2, 3, 4], 
                [5, 2, 4, 2], 
                [1, 2, 0, 1]])
print ("Original :\n", arr, "\n")

"""
(function) def reshape(
    a: ArrayLike,
    newshape: _ShapeLike,
    order: _OrderACF = ...
) -> NDArray[Any]
"""

# auto filled reshape
arr_auto_reshape = np.reshape (arr, (2, -1))
arr_reshap = np.reshape (arr, (2, 2, 3))

print ("Auto reshape (2, -1) :\n", arr_auto_reshape)
print ("Specific reshape (2, 3, 2) :\n", arr_reshap, "\n")

#todo or we can use the method of array to reshape

"""
(method) def reshape(
    *shape: SupportsIndex,
    order: _OrderACF = ...
) -> ndarray[Any, dtype[Any]]
"""

arr_auto_reshape2 = arr.reshape (2, -1)
arr_reshap2 = arr.reshape (2, 2, 3)

print ("Auto reshape (2, -1) :\n", arr_auto_reshape2)
print ("Specific reshape (2, 3, 2) :\n", arr_reshap2)


Original :
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]] 

Auto reshape (2, -1) :
 [[1 2 3 4 5 2]
 [4 2 1 2 0 1]]
Specific reshape (2, 3, 2) :
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]] 

Auto reshape (2, -1) :
 [[1 2 3 4 5 2]
 [4 2 1 2 0 1]]
Specific reshape (2, 3, 2) :
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


#### 2. Flatten

We can flatten the array into only **one dimension** by `flatten ()` :

In [40]:
arr_flatten = arr.flatten ()
print ("Original :\n", arr)
print ("After flatten :\n", arr_flatten)

Original :
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
After flatten :
 [1 2 3 4 5 2 4 2 1 2 0 1]


#### 3. Stacking

Several arrays can be stacked together along different axes.

* `np.vstack` : To stack arrays along **vertical axis**.
* `np.hstack` : To stack arrays along **horizontal axis**.
* `np.column_stack` : To stack 1-D arrays as columns into 2-D arrays.
* `np.concatenate` : To stack arrays **along specified axis** (axis is passed as argument).

In [52]:
a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 
c = np.array ([9, 10])

# vertical stacking
"""
def vstack(
    tup: Sequence[ArrayLike],
    *,
    dtype: _DTypeLike[_SCT@vstack],
    casting: _CastingKind = ...
) -> NDArray[_SCT@vstack]: ...
"""
print ("Vertical Stacking :\n", np.vstack ((a, b)), "\n")

# horizontal stacking
"""
def hstack(
    tup: Sequence[ArrayLike],
    *,
    dtype: _DTypeLike[_SCT@hstack],
    casting: _CastingKind = ...
) -> NDArray[_SCT@hstack]: ...
"""
print ("Horizontal Stacking :\n", np.hstack ((a, b)), "\n")

# stacking columns
"""
(function) def column_stack(tup: Sequence[_ArrayLike[_SCT@column_stack]]) -> NDArray[_SCT@column_stack]
"""
print ("Column Stacking (c, b):\n", np.column_stack ((c, b)))
print ("Column Stacking (b, c):\n", np.column_stack ((b, c)), "\n")

# concatenation
"""
(function) def concatenate(
    arrays: _ArrayLike[_SCT@concatenate],
    /,
    axis: SupportsIndex | None = ...,
    out: None = ...,
    *,
    dtype: None = ...,
    casting: _CastingKind | None = ...
) -> NDArray[_SCT@concatenate]
"""
print ("Concatenation axis 1:\n", np.concatenate ((a, b), 1))
print ("Concatenation axis 0:\n", np.concatenate ((a, b), 0))

Vertical Stacking :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

Horizontal Stacking :
 [[1 2 5 6]
 [3 4 7 8]] 

Column Stacking (c, b):
 [[ 9  5  6]
 [10  7  8]]
Column Stacking (b, c):
 [[ 5  6  9]
 [ 7  8 10]] 

Concatenation axis 1:
 [[1 2 5 6]
 [3 4 7 8]]
Concatenation axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### 4. Splitting

Since we can add the array together, we can also split the array apart.

* `np.hsplit` : Split array along **horizontal** axis.
* `np.vsplit` : Split array along **vertical** axis.
* `np.array_split` : Split array along **specified axis**.


In [53]:
d = np.array ([[1, 3, 5, 7, 9, 11],
               [2, 4, 6, 8, 10, 12]])
print ("Original :\n", d, "\n")

# horizontal splitting
print ("Horizontal Splitting :\n", np.hsplit (d, 2))
print ("Horizontal Splitting :\n", np.hsplit (d, 3), "\n")

# vertical splitting
print ("Vertical Splitting :\n", np.vsplit (d, 1))
print ("Vertical Splitting :\n", np.vsplit (d, 2))

Original :
 [[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]] 

Horizontal Splitting :
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]
Horizontal Splitting :
 [array([[1, 3],
       [2, 4]]), array([[5, 7],
       [6, 8]]), array([[ 9, 11],
       [10, 12]])] 

Vertical Splitting :
 [array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])]
Vertical Splitting :
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]
